/*
 * This file was automatically generated by EvoSuite
 * Sun Jul 05 14:58:32 GMT 2026
 */

package org.apache.openjpa.kernel;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.openjpa.datacache.DataCachePCDataImpl;
import org.apache.openjpa.kernel.PCDataImpl;
import org.apache.openjpa.meta.ClassMetaData;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

// @RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true)
public class PCDataImpl_ESTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      DataCachePCDataImpl dataCachePCDataImpl0 = null;
      try {
        dataCachePCDataImpl0 = new DataCachePCDataImpl((Object) null, (ClassMetaData) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.openjpa.kernel.PCDataImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      PCDataImpl pCDataImpl0 = null;
      try {
        pCDataImpl0 = new PCDataImpl("", (ClassMetaData) null, "");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.openjpa.kernel.PCDataImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      PCDataImpl pCDataImpl0 = null;
      try {
        pCDataImpl0 = new PCDataImpl("", (ClassMetaData) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.openjpa.kernel.PCDataImpl", e);
      }
  }
}
