/*
 * This file was automatically generated by EvoSuite
 * Sun Jul 05 15:24:49 GMT 2026
 */

package org.apache.openjpa.jdbc.kernel.exps;

import org.junit.Ignore;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.InputStream;
import java.io.SequenceInputStream;
import java.sql.Timestamp;
import java.util.Enumeration;
import java.util.NoSuchElementException;
import org.apache.openjpa.jdbc.kernel.DelegatingJDBCFetchConfiguration;
import org.apache.openjpa.jdbc.kernel.JDBCFetchConfiguration;
import org.apache.openjpa.jdbc.kernel.JDBCFetchConfigurationImpl;
import org.apache.openjpa.jdbc.kernel.JDBCStore;
import org.apache.openjpa.jdbc.kernel.JDBCStoreManager;
import org.apache.openjpa.jdbc.kernel.exps.All;
import org.apache.openjpa.jdbc.kernel.exps.BinaryOpExpState;
import org.apache.openjpa.jdbc.kernel.exps.ConstPath;
import org.apache.openjpa.jdbc.kernel.exps.Count;
import org.apache.openjpa.jdbc.kernel.exps.CurrentDate;
import org.apache.openjpa.jdbc.kernel.exps.ExpContext;
import org.apache.openjpa.jdbc.kernel.exps.ExpState;
import org.apache.openjpa.jdbc.kernel.exps.PCPath;
import org.apache.openjpa.jdbc.kernel.exps.SubQ;
import org.apache.openjpa.jdbc.kernel.exps.TypeLit;
import org.apache.openjpa.jdbc.kernel.exps.Variable;
import org.apache.openjpa.jdbc.meta.ClassMapping;
import org.apache.openjpa.jdbc.meta.strats.HandlerRelationMapTableFieldStrategy;
import org.apache.openjpa.jdbc.meta.strats.RelationMapInverseKeyFieldStrategy;
import org.apache.openjpa.jdbc.meta.strats.RelationMapTableFieldStrategy;
import org.apache.openjpa.jdbc.sql.Joins;
import org.apache.openjpa.jdbc.sql.SQLBuffer;
import org.apache.openjpa.jdbc.sql.Select;
import org.apache.openjpa.kernel.StoreContext;
import org.apache.openjpa.meta.ClassMetaData;
import org.apache.openjpa.meta.FieldMetaData;
import org.apache.openjpa.meta.XMLFieldMetaData;
import org.apache.openjpa.meta.XMLMetaData;
import org.apache.openjpa.util.RuntimeExceptionTranslator;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

// @RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true)
public class PCPath_ESTest {

    @Test(timeout = 4000)
    public void test00()  throws Throwable  {
        Class<HandlerRelationMapTableFieldStrategy> class0 = HandlerRelationMapTableFieldStrategy.class;
        Variable variable0 = new Variable((String) null, class0);
        PCPath pCPath0 = new PCPath((ClassMapping) null, variable0);
        pCPath0.get((FieldMetaData) null, (XMLMetaData) null);
        boolean boolean0 = pCPath0.isVariable();
        assertTrue(pCPath0.isXPath());
        assertFalse(boolean0);
    }

    @Test(timeout = 4000)
    public void test01()  throws Throwable  {
        Class<SubQ> class0 = SubQ.class;
        Variable variable0 = new Variable("", class0);
        PCPath pCPath0 = new PCPath((ClassMapping) null, variable0);
        pCPath0.get((FieldMetaData) null, false);
        pCPath0.setContainsId((String) null);
        assertTrue(pCPath0.isVariable());
    }

    @Test(timeout = 4000)
    public void test02()  throws Throwable  {
        Class<HandlerRelationMapTableFieldStrategy> class0 = HandlerRelationMapTableFieldStrategy.class;
        Variable variable0 = new Variable((String) null, class0);
        PCPath pCPath0 = new PCPath((ClassMapping) null, variable0);
        pCPath0.get((FieldMetaData) null, (XMLMetaData) null);
        boolean boolean0 = pCPath0.isUnaccessedVariable();
        assertTrue(pCPath0.isXPath());
        assertFalse(boolean0);
    }

    @Test(timeout = 4000)
    public void test03()  throws Throwable  {
        Class<HandlerRelationMapTableFieldStrategy> class0 = HandlerRelationMapTableFieldStrategy.class;
        Variable variable0 = new Variable((String) null, class0);
        PCPath pCPath0 = new PCPath((ClassMapping) null, variable0);
        XMLFieldMetaData xMLFieldMetaData0 = new XMLFieldMetaData(class0, "openjpa");
        pCPath0.get((XMLMetaData) xMLFieldMetaData0, "B<>!._J]");
        assertTrue(pCPath0.isXPath());
    }

    @Test(timeout = 4000)
    public void test04()  throws Throwable  {
        Class<HandlerRelationMapTableFieldStrategy> class0 = HandlerRelationMapTableFieldStrategy.class;
        Variable variable0 = new Variable((String) null, class0);
        PCPath pCPath0 = new PCPath((ClassMapping) null, variable0);
        pCPath0.get((FieldMetaData) null, false);
        pCPath0.getKey();
        boolean boolean0 = pCPath0.isKey();
        assertFalse(pCPath0.isVariable());
        assertTrue(boolean0);
    }

    @Test(timeout = 4000)
    public void test05()  throws Throwable  {
        Class<HandlerRelationMapTableFieldStrategy> class0 = HandlerRelationMapTableFieldStrategy.class;
        Variable variable0 = new Variable((String) null, class0);
        PCPath pCPath0 = new PCPath((ClassMapping) null, variable0);
        assertTrue(pCPath0.isVariable());

        pCPath0.get((FieldMetaData) null, false);
        pCPath0.getXmlMapping();
        assertTrue(pCPath0.isVariablePath());
    }

    @Test(timeout = 4000)
    public void test06()  throws Throwable  {
        Class<Integer> class0 = Integer.class;
        Variable variable0 = new Variable("`syn", class0);
        PCPath pCPath0 = new PCPath((ClassMapping) null, variable0);
        String string0 = pCPath0.getSchemaAlias();
        assertFalse(pCPath0.isUnaccessedVariable());
        assertEquals("`syn", string0);
        assertTrue(pCPath0.isVariablePath());
        assertFalse(pCPath0.isKey());
        assertFalse(pCPath0.isSubqueryPath());
    }

    @Test(timeout = 4000)
    public void test07()  throws Throwable  {
        Class<SubQ> class0 = SubQ.class;
        Variable variable0 = new Variable("", class0);
        PCPath pCPath0 = new PCPath((ClassMapping) null, variable0);
        PCPath.PathExpState pCPath_PathExpState0 = new PCPath.PathExpState((Joins) null);
        pCPath0.getFieldMapping(pCPath_PathExpState0);
        assertFalse(pCPath_PathExpState0.joinedRel);
        assertFalse(pCPath0.isUnaccessedVariable());
        assertFalse(pCPath0.isKey());
        assertTrue(pCPath0.isVariablePath());
        assertFalse(pCPath_PathExpState0.isEmbedElementColl);
        assertTrue(pCPath0.isVariable());
    }

    @Test(timeout = 4000)
    @Ignore
    public void test08()  throws Throwable  {
        JDBCStoreManager jDBCStoreManager0 = new JDBCStoreManager();
        Object[] objectArray0 = new Object[4];
        JDBCFetchConfigurationImpl jDBCFetchConfigurationImpl0 = new JDBCFetchConfigurationImpl();
        RuntimeExceptionTranslator runtimeExceptionTranslator0 = mock(RuntimeExceptionTranslator.class, new ViolatedAssumptionAnswer());
        DelegatingJDBCFetchConfiguration delegatingJDBCFetchConfiguration0 = new DelegatingJDBCFetchConfiguration(jDBCFetchConfigurationImpl0, runtimeExceptionTranslator0);
        ExpContext expContext0 = new ExpContext(jDBCStoreManager0, objectArray0, delegatingJDBCFetchConfiguration0);
        Class<HandlerRelationMapTableFieldStrategy> class0 = HandlerRelationMapTableFieldStrategy.class;
        Variable variable0 = new Variable((String) null, class0);
        PCPath pCPath0 = new PCPath((ClassMapping) null, variable0);
        All all0 = new All(variable0);
        ExpState expState0 = all0.initialize((Select) null, expContext0, 0);
        // Undeclared exception!
        try {
            pCPath0.selectColumns((Select) null, expContext0, expState0, false);
            fail("Expecting exception: NullPointerException");

        } catch(NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("org.apache.openjpa.jdbc.kernel.exps.PCPath", e);
        }
    }

    @Test(timeout = 4000)
    public void test09()  throws Throwable  {
        Class<RelationMapInverseKeyFieldStrategy> class0 = RelationMapInverseKeyFieldStrategy.class;
        Variable variable0 = new Variable("Y4S+)ou", class0);
        PCPath pCPath0 = new PCPath((ClassMapping) null, variable0);
        JDBCStoreManager jDBCStoreManager0 = new JDBCStoreManager();
        Object[] objectArray0 = new Object[7];
        ExpContext expContext0 = new ExpContext(jDBCStoreManager0, objectArray0, (JDBCFetchConfiguration) null);
        // Undeclared exception!
        try {
            pCPath0.initialize((Select) null, expContext0, 0);
            fail("Expecting exception: NullPointerException");

        } catch(NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("org.apache.openjpa.jdbc.kernel.exps.PCPath", e);
        }
    }

    @Test(timeout = 4000)
    @Ignore
    public void test10()  throws Throwable  {
        JDBCStoreManager jDBCStoreManager0 = new JDBCStoreManager();
        Object[] objectArray0 = new Object[5];
        JDBCFetchConfigurationImpl jDBCFetchConfigurationImpl0 = new JDBCFetchConfigurationImpl();
        RuntimeExceptionTranslator runtimeExceptionTranslator0 = mock(RuntimeExceptionTranslator.class, new ViolatedAssumptionAnswer());
        DelegatingJDBCFetchConfiguration delegatingJDBCFetchConfiguration0 = new DelegatingJDBCFetchConfiguration(jDBCFetchConfigurationImpl0, runtimeExceptionTranslator0);
        ExpContext expContext0 = new ExpContext(jDBCStoreManager0, objectArray0, delegatingJDBCFetchConfiguration0);
        Class<HandlerRelationMapTableFieldStrategy> class0 = HandlerRelationMapTableFieldStrategy.class;
        Variable variable0 = new Variable((String) null, class0);
        PCPath pCPath0 = new PCPath((ClassMapping) null, variable0);
        All all0 = new All(variable0);
        ExpState expState0 = all0.initialize((Select) null, expContext0, 0);
        // Undeclared exception!
        try {
            pCPath0.groupBy((Select) null, expContext0, expState0);
            fail("Expecting exception: ClassCastException");

        } catch(ClassCastException e) {
            //
            // org.apache.openjpa.jdbc.kernel.exps.ExpState cannot be cast to org.apache.openjpa.jdbc.kernel.exps.PCPath$PathExpState
            //
            verifyException("org.apache.openjpa.jdbc.kernel.exps.PCPath", e);
        }
    }

    @Test(timeout = 4000)
    public void test11()  throws Throwable  {
        PCPath pCPath0 = new PCPath((ClassMapping) null);
        // Undeclared exception!
        try {
            pCPath0.getXPath();
            fail("Expecting exception: NullPointerException");

        } catch(NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("org.apache.openjpa.jdbc.kernel.exps.PCPath", e);
        }
    }

    @Test(timeout = 4000)
    public void test12()  throws Throwable  {
        Class<RelationMapTableFieldStrategy> class0 = RelationMapTableFieldStrategy.class;
        Variable variable0 = new Variable("", class0);
        PCPath pCPath0 = new PCPath((ClassMapping) null, variable0);
        // Undeclared exception!
        try {
            pCPath0.getKey();
            fail("Expecting exception: NullPointerException");

        } catch(NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("org.apache.openjpa.jdbc.kernel.exps.PCPath", e);
        }
    }

    @Test(timeout = 4000)
    public void test13()  throws Throwable  {
        PCPath pCPath0 = new PCPath((ClassMapping) null);
        // Undeclared exception!
        try {
            pCPath0.getFieldMapping((ExpState) null);
            fail("Expecting exception: NullPointerException");

        } catch(NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("org.apache.openjpa.jdbc.kernel.exps.PCPath", e);
        }
    }

    @Test(timeout = 4000)
    public void test14()  throws Throwable  {
        ExpContext expContext0 = new ExpContext();
        Class<SubQ> class0 = SubQ.class;
        Variable variable0 = new Variable("", class0);
        PCPath pCPath0 = new PCPath((ClassMapping) null, variable0);
        Count count0 = new Count(variable0);
        ExpState expState0 = count0.initialize((Select) null, expContext0, 153);
        BinaryOpExpState binaryOpExpState0 = new BinaryOpExpState((Joins) null, expState0, expState0);
        // Undeclared exception!
        try {
            pCPath0.getColumns(binaryOpExpState0);
            fail("Expecting exception: ClassCastException");

        } catch(ClassCastException e) {
            //
            // org.apache.openjpa.jdbc.kernel.exps.BinaryOpExpState cannot be cast to org.apache.openjpa.jdbc.kernel.exps.PCPath$PathExpState
            //
            verifyException("org.apache.openjpa.jdbc.kernel.exps.PCPath", e);
        }
    }

    @Test(timeout = 4000)
    public void test15()  throws Throwable  {
        Class<RelationMapTableFieldStrategy> class0 = RelationMapTableFieldStrategy.class;
        Variable variable0 = new Variable("x1|=],I.'", class0);
        PCPath pCPath0 = new PCPath((ClassMapping) null, variable0);
        // Undeclared exception!
        try {
            pCPath0.getClassMapping((ExpState) null);
            fail("Expecting exception: NullPointerException");

        } catch(NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("org.apache.openjpa.jdbc.kernel.exps.PCPath", e);
        }
    }

    @Test(timeout = 4000)
    @Ignore
    public void test16()  throws Throwable  {
        JDBCStoreManager jDBCStoreManager0 = new JDBCStoreManager();
        Object[] objectArray0 = new Object[5];
        JDBCFetchConfigurationImpl jDBCFetchConfigurationImpl0 = new JDBCFetchConfigurationImpl();
        RuntimeExceptionTranslator runtimeExceptionTranslator0 = mock(RuntimeExceptionTranslator.class, new ViolatedAssumptionAnswer());
        DelegatingJDBCFetchConfiguration delegatingJDBCFetchConfiguration0 = new DelegatingJDBCFetchConfiguration(jDBCFetchConfigurationImpl0, runtimeExceptionTranslator0);
        ExpContext expContext0 = new ExpContext(jDBCStoreManager0, objectArray0, delegatingJDBCFetchConfiguration0);
        Class<HandlerRelationMapTableFieldStrategy> class0 = HandlerRelationMapTableFieldStrategy.class;
        Variable variable0 = new Variable((String) null, class0);
        PCPath pCPath0 = new PCPath((ClassMapping) null, variable0);
        All all0 = new All(variable0);
        ExpState expState0 = all0.initialize((Select) null, expContext0, 0);
        // Undeclared exception!
        try {
            pCPath0.getClassMapping(expState0);
            fail("Expecting exception: ClassCastException");

        } catch(ClassCastException e) {
            //
            // org.apache.openjpa.jdbc.kernel.exps.ExpState cannot be cast to org.apache.openjpa.jdbc.kernel.exps.PCPath$PathExpState
            //
            verifyException("org.apache.openjpa.jdbc.kernel.exps.PCPath", e);
        }
    }

    @Test(timeout = 4000)
    public void test17()  throws Throwable  {
        PCPath pCPath0 = new PCPath((ClassMapping) null);
        Object[] objectArray0 = new Object[3];
        JDBCFetchConfigurationImpl jDBCFetchConfigurationImpl0 = new JDBCFetchConfigurationImpl();
        ExpContext expContext0 = new ExpContext((JDBCStore) null, objectArray0, jDBCFetchConfigurationImpl0);
        // Undeclared exception!
        try {
            pCPath0.appendIsNotNull((Select) null, expContext0, (ExpState) null, (SQLBuffer) null);
            fail("Expecting exception: NullPointerException");

        } catch(NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("org.apache.openjpa.jdbc.kernel.exps.PCPath", e);
        }
    }

    @Test(timeout = 4000)
    @Ignore
    public void test18()  throws Throwable  {
        JDBCStoreManager jDBCStoreManager0 = new JDBCStoreManager();
        Object[] objectArray0 = new Object[5];
        JDBCFetchConfigurationImpl jDBCFetchConfigurationImpl0 = new JDBCFetchConfigurationImpl();
        RuntimeExceptionTranslator runtimeExceptionTranslator0 = mock(RuntimeExceptionTranslator.class, new ViolatedAssumptionAnswer());
        DelegatingJDBCFetchConfiguration delegatingJDBCFetchConfiguration0 = new DelegatingJDBCFetchConfiguration(jDBCFetchConfigurationImpl0, runtimeExceptionTranslator0);
        ExpContext expContext0 = new ExpContext(jDBCStoreManager0, objectArray0, delegatingJDBCFetchConfiguration0);
        Class<HandlerRelationMapTableFieldStrategy> class0 = HandlerRelationMapTableFieldStrategy.class;
        Variable variable0 = new Variable((String) null, class0);
        PCPath pCPath0 = new PCPath((ClassMapping) null, variable0);
        All all0 = new All(variable0);
        ExpState expState0 = all0.initialize((Select) null, expContext0, 0);
        // Undeclared exception!
        try {
            pCPath0.appendIndex((Select) null, expContext0, expState0, (SQLBuffer) null);
            fail("Expecting exception: ClassCastException");

        } catch(ClassCastException e) {
            //
            // org.apache.openjpa.jdbc.kernel.exps.ExpState cannot be cast to org.apache.openjpa.jdbc.kernel.exps.PCPath$PathExpState
            //
            verifyException("org.apache.openjpa.jdbc.kernel.exps.PCPath", e);
        }
    }

    @Test(timeout = 4000)
    public void test19()  throws Throwable  {
        PCPath pCPath0 = null;
        try {
            pCPath0 = new PCPath((ClassMapping) null, (Variable) null);
            fail("Expecting exception: NullPointerException");

        } catch(NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("org.apache.openjpa.jdbc.kernel.exps.PCPath", e);
        }
    }

    @Test(timeout = 4000)
    public void test20()  throws Throwable  {
        Class<HandlerRelationMapTableFieldStrategy> class0 = HandlerRelationMapTableFieldStrategy.class;
        Variable variable0 = new Variable((String) null, class0);
        PCPath pCPath0 = new PCPath((ClassMapping) null, variable0);
        assertTrue(pCPath0.isVariable());

        pCPath0.get((FieldMetaData) null, (XMLMetaData) null);
        boolean boolean0 = pCPath0.isXPath();
        assertTrue(boolean0);
    }

    @Test(timeout = 4000)
    public void test21()  throws Throwable  {
        Class<HandlerRelationMapTableFieldStrategy> class0 = HandlerRelationMapTableFieldStrategy.class;
        Variable variable0 = new Variable((String) null, class0);
        PCPath pCPath0 = new PCPath((ClassMapping) null, variable0);
        boolean boolean0 = pCPath0.isXPath();
        assertFalse(boolean0);
        assertTrue(pCPath0.isVariablePath());
        assertFalse(pCPath0.isKey());
        assertFalse(pCPath0.isSubqueryPath());
        assertFalse(pCPath0.isUnaccessedVariable());
    }

    @Test(timeout = 4000)
    public void test22()  throws Throwable  {
        PCPath pCPath0 = new PCPath((ClassMapping) null);
        boolean boolean0 = pCPath0.equals((Object) null);
        assertFalse(pCPath0.isKey());
        assertFalse(pCPath0.isVariablePath());
        assertFalse(boolean0);
    }

    @Test(timeout = 4000)
    public void test23()  throws Throwable  {
        PCPath pCPath0 = new PCPath((ClassMapping) null);
        // Undeclared exception!
        try {
            pCPath0.hashCode();
            fail("Expecting exception: NullPointerException");

        } catch(NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("org.apache.openjpa.jdbc.kernel.exps.PCPath", e);
        }
    }

    @Test(timeout = 4000)
    public void test24()  throws Throwable  {
        Class<HandlerRelationMapTableFieldStrategy> class0 = HandlerRelationMapTableFieldStrategy.class;
        Variable variable0 = new Variable((String) null, class0);
        PCPath pCPath0 = new PCPath((ClassMapping) null, variable0);
        // Undeclared exception!
        try {
            pCPath0.hashCode();
            fail("Expecting exception: NullPointerException");

        } catch(NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("org.apache.openjpa.jdbc.kernel.exps.PCPath", e);
        }
    }

    @Test(timeout = 4000)
    public void test25()  throws Throwable  {
        Class<HandlerRelationMapTableFieldStrategy> class0 = HandlerRelationMapTableFieldStrategy.class;
        Variable variable0 = new Variable((String) null, class0);
        PCPath pCPath0 = new PCPath((ClassMapping) null, variable0);
        assertTrue(pCPath0.isVariable());

        pCPath0.get((FieldMetaData) null, false);
        boolean boolean0 = pCPath0.isSubqueryPath();
        assertFalse(boolean0);
    }

    @Test(timeout = 4000)
    public void test26()  throws Throwable  {
        Class<SubQ> class0 = SubQ.class;
        Variable variable0 = new Variable("", class0);
        PCPath pCPath0 = new PCPath((ClassMapping) null, variable0);
        boolean boolean0 = pCPath0.isSubqueryPath();
        assertFalse(pCPath0.isKey());
        assertTrue(pCPath0.isVariablePath());
        assertFalse(boolean0);
        assertFalse(pCPath0.isUnaccessedVariable());
    }

    @Test(timeout = 4000)
    public void test27()  throws Throwable  {
        PCPath pCPath0 = new PCPath((ClassMapping) null);
        boolean boolean0 = pCPath0.isSubqueryPath();
        assertFalse(pCPath0.isVariablePath());
        assertFalse(boolean0);
        assertFalse(pCPath0.isKey());
    }

    @Test(timeout = 4000)
    public void test28()  throws Throwable  {
        PCPath pCPath0 = new PCPath((ClassMapping) null);
        pCPath0.eval((Object) null, (Object) null, (StoreContext) null, (Object[]) null);
        assertFalse(pCPath0.isVariablePath());
        assertFalse(pCPath0.isKey());
    }

    @Test(timeout = 4000)
    public void test29()  throws Throwable  {
        Class<SubQ> class0 = SubQ.class;
        Variable variable0 = new Variable("", class0);
        PCPath pCPath0 = new PCPath((ClassMapping) null, variable0);
        // Undeclared exception!
        try {
            pCPath0.eval((Object) null, (Object) null, (StoreContext) null, (Object[]) null);
            fail("Expecting exception: NullPointerException");

        } catch(NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("org.apache.openjpa.jdbc.kernel.exps.PCPath", e);
        }
    }

    @Test(timeout = 4000)
    public void test30()  throws Throwable  {
        Class<RelationMapTableFieldStrategy> class0 = RelationMapTableFieldStrategy.class;
        Variable variable0 = new Variable("x1|=],I.'", class0);
        PCPath pCPath0 = new PCPath((ClassMapping) null, variable0);
        Class class1 = pCPath0.getType();
        assertEquals("class org.apache.openjpa.jdbc.meta.strats.RelationMapTableFieldStrategy", class1.toString());
        assertTrue(pCPath0.isVariablePath());
        assertFalse(pCPath0.isUnaccessedVariable());
        assertFalse(pCPath0.isKey());
        assertTrue(pCPath0.isVariable());
    }

    @Test(timeout = 4000)
    public void test31()  throws Throwable  {
        Class<HandlerRelationMapTableFieldStrategy> class0 = HandlerRelationMapTableFieldStrategy.class;
        Variable variable0 = new Variable((String) null, class0);
        PCPath pCPath0 = new PCPath((ClassMapping) null, variable0);
        pCPath0.get((FieldMetaData) null, false);
        pCPath0.getKey();
        // Undeclared exception!
        try {
            pCPath0.verifyIndexedField();
            fail("Expecting exception: NullPointerException");

        } catch(NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("org.apache.openjpa.jdbc.kernel.exps.PCPath", e);
        }
    }

    @Test(timeout = 4000)
    public void test32()  throws Throwable  {
        PCPath pCPath0 = new PCPath((ClassMapping) null);
        pCPath0.last();
        assertFalse(pCPath0.isKey());
        assertFalse(pCPath0.isVariablePath());
    }

    @Test(timeout = 4000)
    public void test33()  throws Throwable  {
        Class<HandlerRelationMapTableFieldStrategy> class0 = HandlerRelationMapTableFieldStrategy.class;
        Variable variable0 = new Variable((String) null, class0);
        PCPath pCPath0 = new PCPath((ClassMapping) null, variable0);
        assertTrue(pCPath0.isVariable());

        pCPath0.get((FieldMetaData) null, (XMLMetaData) null);
        pCPath0.last();
        assertTrue(pCPath0.isXPath());
    }

    @Test(timeout = 4000)
    public void test34()  throws Throwable  {
        Class<SubQ> class0 = SubQ.class;
        Variable variable0 = new Variable("", class0);
        PCPath pCPath0 = new PCPath((ClassMapping) null, variable0);
        assertTrue(pCPath0.isVariable());

        pCPath0.get((FieldMetaData) null, false);
        pCPath0.last();
        assertFalse(pCPath0.isXPath());
    }

    @Test(timeout = 4000)
    public void test35()  throws Throwable  {
        Class<HandlerRelationMapTableFieldStrategy> class0 = HandlerRelationMapTableFieldStrategy.class;
        Variable variable0 = new Variable((String) null, class0);
        PCPath pCPath0 = new PCPath((ClassMapping) null, variable0);
        // Undeclared exception!
        try {
            pCPath0.getXmlMapping();
            fail("Expecting exception: ClassCastException");

        } catch(ClassCastException e) {
            //
            // org.apache.openjpa.jdbc.kernel.exps.Variable cannot be cast to org.apache.openjpa.meta.XMLMetaData
            //
            verifyException("org.apache.openjpa.jdbc.kernel.exps.PCPath", e);
        }
    }

    @Test(timeout = 4000)
    public void test36()  throws Throwable  {
        Class<HandlerRelationMapTableFieldStrategy> class0 = HandlerRelationMapTableFieldStrategy.class;
        Variable variable0 = new Variable((String) null, class0);
        PCPath pCPath0 = new PCPath((ClassMapping) null, variable0);
        pCPath0.get((FieldMetaData) null, true);
        pCPath0.getKey();
        assertTrue(pCPath0.isKey());
    }

    @Test(timeout = 4000)
    public void test37()  throws Throwable  {
        PCPath pCPath0 = new PCPath((ClassMapping) null);
        pCPath0.get((FieldMetaData) null, false);
        assertFalse(pCPath0.isVariablePath());
        assertFalse(pCPath0.isKey());
    }

    @Test(timeout = 4000)
    public void test38()  throws Throwable  {
        Class<HandlerRelationMapTableFieldStrategy> class0 = HandlerRelationMapTableFieldStrategy.class;
        Variable variable0 = new Variable((String) null, class0);
        PCPath pCPath0 = new PCPath((ClassMapping) null, variable0);
        assertTrue(pCPath0.isVariable());

        pCPath0.get((FieldMetaData) null, false);
        boolean boolean0 = pCPath0.isVariable();
        assertFalse(boolean0);
    }

    @Test(timeout = 4000)
    public void test39()  throws Throwable  {
        PCPath pCPath0 = new PCPath((ClassMapping) null);
        boolean boolean0 = pCPath0.isVariable();
        assertFalse(pCPath0.isKey());
        assertFalse(pCPath0.isVariablePath());
        assertFalse(boolean0);
    }

    @Test(timeout = 4000)
    public void test40()  throws Throwable  {
        Class<HandlerRelationMapTableFieldStrategy> class0 = HandlerRelationMapTableFieldStrategy.class;
        Variable variable0 = new Variable((String) null, class0);
        PCPath pCPath0 = new PCPath((ClassMapping) null, variable0);
        boolean boolean0 = pCPath0.isVariable();
        assertFalse(pCPath0.isUnaccessedVariable());
        assertTrue(boolean0);
        assertTrue(pCPath0.isVariablePath());
        assertFalse(pCPath0.isKey());
    }

    @Test(timeout = 4000)
    public void test41()  throws Throwable  {
        Class<HandlerRelationMapTableFieldStrategy> class0 = HandlerRelationMapTableFieldStrategy.class;
        Variable variable0 = new Variable((String) null, class0);
        PCPath pCPath0 = new PCPath((ClassMapping) null, variable0);
        pCPath0.get((FieldMetaData) null, false);
        // Undeclared exception!
        try {
            pCPath0.getPCPathString();
            fail("Expecting exception: NullPointerException");

        } catch(NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("org.apache.openjpa.jdbc.kernel.exps.PCPath", e);
        }
    }

    @Test(timeout = 4000)
    public void test42()  throws Throwable  {
        PCPath pCPath0 = new PCPath((ClassMapping) null);
        String string0 = pCPath0.getPCPathString();
        assertEquals("", string0);
        assertFalse(pCPath0.isKey());
        assertFalse(pCPath0.isVariablePath());
    }

    @Test(timeout = 4000)
    public void test43()  throws Throwable  {
        Class<Integer> class0 = Integer.class;
        Variable variable0 = new Variable("`syn", class0);
        PCPath pCPath0 = new PCPath((ClassMapping) null, variable0);
        String string0 = pCPath0.getPCPathString();
        assertEquals("`syn.", string0);
        assertTrue(pCPath0.isVariable());
        assertFalse(pCPath0.isUnaccessedVariable());
        assertFalse(pCPath0.isKey());
        assertTrue(pCPath0.isVariablePath());
    }

    @Test(timeout = 4000)
    public void test44()  throws Throwable  {
        Class<HandlerRelationMapTableFieldStrategy> class0 = HandlerRelationMapTableFieldStrategy.class;
        Variable variable0 = new Variable((String) null, class0);
        PCPath pCPath0 = new PCPath((ClassMapping) null, variable0);
        pCPath0.get((FieldMetaData) null, (XMLMetaData) null);
        pCPath0.getXPath();
        assertTrue(pCPath0.isXPath());
    }

    @Test(timeout = 4000)
    public void test45()  throws Throwable  {
        Class<Integer> class0 = Integer.class;
        Variable variable0 = new Variable("`syn", class0);
        PCPath pCPath0 = new PCPath((ClassMapping) null, variable0);
        // Undeclared exception!
        try {
            pCPath0.getXPath();
            fail("Expecting exception: NoSuchElementException");

        } catch(NoSuchElementException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("java.util.LinkedList$ListItr", e);
        }
    }

    @Test(timeout = 4000)
    public void test46()  throws Throwable  {
        Class<HandlerRelationMapTableFieldStrategy> class0 = HandlerRelationMapTableFieldStrategy.class;
        Variable variable0 = new Variable((String) null, class0);
        PCPath pCPath0 = new PCPath((ClassMapping) null, variable0);
        pCPath0.get((FieldMetaData) null, (XMLMetaData) null);
        // Undeclared exception!
        try {
            pCPath0.getType();
            fail("Expecting exception: NullPointerException");

        } catch(NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("org.apache.openjpa.jdbc.kernel.exps.PCPath", e);
        }
    }

    @Test(timeout = 4000)
    public void test47()  throws Throwable  {
        PCPath pCPath0 = new PCPath((ClassMapping) null);
        pCPath0.setContainsId((String) null);
        assertTrue(pCPath0.isVariable());
    }

    @Test(timeout = 4000)
    public void test48()  throws Throwable  {
        Class<SubQ> class0 = SubQ.class;
        Variable variable0 = new Variable("", class0);
        PCPath pCPath0 = new PCPath((ClassMapping) null, variable0);
        pCPath0.setContainsId((String) null);
        assertTrue(pCPath0.isVariable());
        assertFalse(pCPath0.isUnaccessedVariable());
        assertFalse(pCPath0.isKey());
        assertTrue(pCPath0.isVariablePath());
    }

    @Test(timeout = 4000)
    public void test49()  throws Throwable  {
        Class<HandlerRelationMapTableFieldStrategy> class0 = HandlerRelationMapTableFieldStrategy.class;
        Variable variable0 = new Variable((String) null, class0);
        PCPath pCPath0 = new PCPath((ClassMapping) null, variable0);
        boolean boolean0 = pCPath0.isVariablePath();
        assertFalse(pCPath0.isUnaccessedVariable());
        assertTrue(pCPath0.isVariable());
        assertTrue(boolean0);
        assertFalse(pCPath0.isKey());
    }

    @Test(timeout = 4000)
    public void test50()  throws Throwable  {
        Class<HandlerRelationMapTableFieldStrategy> class0 = HandlerRelationMapTableFieldStrategy.class;
        Variable variable0 = new Variable((String) null, class0);
        PCPath pCPath0 = new PCPath((ClassMapping) null, variable0);
        pCPath0.get((FieldMetaData) null, false);
        pCPath0.getKey();
        boolean boolean0 = pCPath0.isVariablePath();
        assertTrue(pCPath0.isKey());
        assertFalse(boolean0);
    }

    @Test(timeout = 4000)
    public void test51()  throws Throwable  {
        PCPath pCPath0 = new PCPath((ClassMapping) null);
        boolean boolean0 = pCPath0.isUnaccessedVariable();
        assertFalse(boolean0);
        assertFalse(pCPath0.isVariablePath());
        assertFalse(pCPath0.isKey());
    }

    @Test(timeout = 4000)
    public void test52()  throws Throwable  {
        PCPath pCPath0 = new PCPath((ClassMapping) null);
        pCPath0.setSchemaAlias("m=");
        assertFalse(pCPath0.isVariablePath());
        assertFalse(pCPath0.isKey());
        assertEquals("m=", pCPath0.getSchemaAlias());
    }

    @Test(timeout = 4000)
    public void test53()  throws Throwable  {
        Class<RelationMapTableFieldStrategy> class0 = RelationMapTableFieldStrategy.class;
        Variable variable0 = new Variable("x1|=],I.'", class0);
        PCPath pCPath0 = new PCPath((ClassMapping) null, variable0);
        pCPath0.setSchemaAlias("~giJ$enb{p*bl'r");
        assertFalse(pCPath0.isUnaccessedVariable());
        assertFalse(pCPath0.isKey());
        assertTrue(pCPath0.isVariable());
        assertEquals("x1|=],I.'", pCPath0.getSchemaAlias());
        assertTrue(pCPath0.isVariablePath());
    }

    @Test(timeout = 4000)
    public void test54()  throws Throwable  {
        Class<HandlerRelationMapTableFieldStrategy> class0 = HandlerRelationMapTableFieldStrategy.class;
        Variable variable0 = new Variable((String) null, class0);
        PCPath pCPath0 = new PCPath((ClassMapping) null, variable0);
        Class<RelationMapInverseKeyFieldStrategy> class1 = RelationMapInverseKeyFieldStrategy.class;
        pCPath0.setImplicitType(class1);
        assertFalse(pCPath0.isUnaccessedVariable());
        assertFalse(pCPath0.isKey());
        assertTrue(pCPath0.isVariablePath());
        assertTrue(pCPath0.isVariable());
    }

    @Test(timeout = 4000)
    @Ignore
    public void test55()  throws Throwable  {
        JDBCStoreManager jDBCStoreManager0 = new JDBCStoreManager();
        Object[] objectArray0 = new Object[5];
        JDBCFetchConfigurationImpl jDBCFetchConfigurationImpl0 = new JDBCFetchConfigurationImpl();
        RuntimeExceptionTranslator runtimeExceptionTranslator0 = mock(RuntimeExceptionTranslator.class, new ViolatedAssumptionAnswer());
        DelegatingJDBCFetchConfiguration delegatingJDBCFetchConfiguration0 = new DelegatingJDBCFetchConfiguration(jDBCFetchConfigurationImpl0, runtimeExceptionTranslator0);
        ExpContext expContext0 = new ExpContext(jDBCStoreManager0, objectArray0, delegatingJDBCFetchConfiguration0);
        Class<HandlerRelationMapTableFieldStrategy> class0 = HandlerRelationMapTableFieldStrategy.class;
        Variable variable0 = new Variable((String) null, class0);
        PCPath pCPath0 = new PCPath((ClassMapping) null, variable0);
        All all0 = new All(variable0);
        ExpState expState0 = all0.initialize((Select) null, expContext0, 0);
        Class<Timestamp> class1 = Timestamp.class;
        CurrentDate currentDate0 = new CurrentDate(class1);
        ConstPath constPath0 = new ConstPath(currentDate0);
        pCPath0.calculateValue((Select) null, expContext0, expState0, constPath0, expState0);
        assertTrue(pCPath0.isVariablePath());
        assertFalse(pCPath0.isKey());
        assertFalse(pCPath0.isUnaccessedVariable());
        assertTrue(pCPath0.isVariable());
    }

    @Test(timeout = 4000)
    public void test56()  throws Throwable  {
        Class<HandlerRelationMapTableFieldStrategy> class0 = HandlerRelationMapTableFieldStrategy.class;
        Variable variable0 = new Variable((String) null, class0);
        PCPath pCPath0 = new PCPath((ClassMapping) null, variable0);
        pCPath0.getMetaData();
        assertFalse(pCPath0.isUnaccessedVariable());
        assertTrue(pCPath0.isVariable());
        assertTrue(pCPath0.isVariablePath());
        assertFalse(pCPath0.isKey());
    }

    @Test(timeout = 4000)
    public void test57()  throws Throwable  {
        Class<SubQ> class0 = SubQ.class;
        Variable variable0 = new Variable("", class0);
        PCPath pCPath0 = new PCPath((ClassMapping) null, variable0);
        // Undeclared exception!
        try {
            pCPath0.get((XMLMetaData) null, "");
            fail("Expecting exception: NullPointerException");

        } catch(NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("org.apache.openjpa.jdbc.kernel.exps.PCPath", e);
        }
    }

    @Test(timeout = 4000)
    @Ignore
    public void test58()  throws Throwable  {
        JDBCStoreManager jDBCStoreManager0 = new JDBCStoreManager();
        Object[] objectArray0 = new Object[5];
        JDBCFetchConfigurationImpl jDBCFetchConfigurationImpl0 = new JDBCFetchConfigurationImpl();
        RuntimeExceptionTranslator runtimeExceptionTranslator0 = mock(RuntimeExceptionTranslator.class, new ViolatedAssumptionAnswer());
        DelegatingJDBCFetchConfiguration delegatingJDBCFetchConfiguration0 = new DelegatingJDBCFetchConfiguration(jDBCFetchConfigurationImpl0, runtimeExceptionTranslator0);
        ExpContext expContext0 = new ExpContext(jDBCStoreManager0, objectArray0, delegatingJDBCFetchConfiguration0);
        Class<HandlerRelationMapTableFieldStrategy> class0 = HandlerRelationMapTableFieldStrategy.class;
        Variable variable0 = new Variable((String) null, class0);
        PCPath pCPath0 = new PCPath((ClassMapping) null, variable0);
        All all0 = new All(variable0);
        ExpState expState0 = all0.initialize((Select) null, expContext0, 0);
        // Undeclared exception!
        try {
            pCPath0.getFieldMapping(expState0);
            fail("Expecting exception: ClassCastException");

        } catch(ClassCastException e) {
            //
            // org.apache.openjpa.jdbc.kernel.exps.ExpState cannot be cast to org.apache.openjpa.jdbc.kernel.exps.PCPath$PathExpState
            //
            verifyException("org.apache.openjpa.jdbc.kernel.exps.PCPath", e);
        }
    }

    @Test(timeout = 4000)
    @Ignore
    public void test59()  throws Throwable  {
        JDBCStoreManager jDBCStoreManager0 = new JDBCStoreManager();
        Object[] objectArray0 = new Object[1];
        JDBCFetchConfigurationImpl jDBCFetchConfigurationImpl0 = new JDBCFetchConfigurationImpl();
        ExpContext expContext0 = new ExpContext(jDBCStoreManager0, objectArray0, jDBCFetchConfigurationImpl0);
        Class<Integer> class0 = Integer.class;
        Variable variable0 = new Variable("`syn", class0);
        PCPath pCPath0 = new PCPath((ClassMapping) null, variable0);
        Enumeration<InputStream> enumeration0 = (Enumeration<InputStream>) mock(Enumeration.class, new ViolatedAssumptionAnswer());
        doReturn(false).when(enumeration0).hasMoreElements();
        SequenceInputStream sequenceInputStream0 = new SequenceInputStream(enumeration0);
        TypeLit typeLit0 = new TypeLit(sequenceInputStream0, 1);
        ExpState expState0 = typeLit0.initialize((Select) null, expContext0, (-1009));
        // Undeclared exception!
        try {
            pCPath0.length((Select) null, expContext0, expState0);
            fail("Expecting exception: ClassCastException");

        } catch(ClassCastException e) {
            //
            // org.apache.openjpa.jdbc.kernel.exps.TypeLit$LitExpState cannot be cast to org.apache.openjpa.jdbc.kernel.exps.PCPath$PathExpState
            //
            verifyException("org.apache.openjpa.jdbc.kernel.exps.PCPath", e);
        }
    }

    @Test(timeout = 4000)
    public void test60()  throws Throwable  {
        PCPath pCPath0 = new PCPath((ClassMapping) null);
        String string0 = pCPath0.getSchemaAlias();
        assertFalse(pCPath0.isVariablePath());
        assertFalse(pCPath0.isKey());
        assertNull(string0);
    }

    @Test(timeout = 4000)
    public void test61()  throws Throwable  {
        Class<RelationMapTableFieldStrategy> class0 = RelationMapTableFieldStrategy.class;
        Variable variable0 = new Variable("x1|=],I.'", class0);
        PCPath pCPath0 = new PCPath((ClassMapping) null, variable0);
        boolean boolean0 = pCPath0.isKey();
        assertTrue(pCPath0.isVariable());
        assertTrue(pCPath0.isVariablePath());
        assertFalse(boolean0);
        assertFalse(pCPath0.isUnaccessedVariable());
    }

    @Test(timeout = 4000)
    @Ignore
    public void test62()  throws Throwable  {
        JDBCStoreManager jDBCStoreManager0 = new JDBCStoreManager();
        Object[] objectArray0 = new Object[5];
        JDBCFetchConfigurationImpl jDBCFetchConfigurationImpl0 = new JDBCFetchConfigurationImpl();
        RuntimeExceptionTranslator runtimeExceptionTranslator0 = mock(RuntimeExceptionTranslator.class, new ViolatedAssumptionAnswer());
        DelegatingJDBCFetchConfiguration delegatingJDBCFetchConfiguration0 = new DelegatingJDBCFetchConfiguration(jDBCFetchConfigurationImpl0, runtimeExceptionTranslator0);
        ExpContext expContext0 = new ExpContext(jDBCStoreManager0, objectArray0, delegatingJDBCFetchConfiguration0);
        Class<HandlerRelationMapTableFieldStrategy> class0 = HandlerRelationMapTableFieldStrategy.class;
        Variable variable0 = new Variable((String) null, class0);
        PCPath pCPath0 = new PCPath((ClassMapping) null, variable0);
        All all0 = new All(variable0);
        ExpState expState0 = all0.initialize((Select) null, expContext0, 0);
        // Undeclared exception!
        try {
            pCPath0.orderBy((Select) null, expContext0, expState0, true);
            fail("Expecting exception: ClassCastException");

        } catch(ClassCastException e) {
            //
            // org.apache.openjpa.jdbc.kernel.exps.ExpState cannot be cast to org.apache.openjpa.jdbc.kernel.exps.PCPath$PathExpState
            //
            verifyException("org.apache.openjpa.jdbc.kernel.exps.PCPath", e);
        }
    }

    @Test(timeout = 4000)
    @Ignore
    public void test63()  throws Throwable  {
        JDBCStoreManager jDBCStoreManager0 = new JDBCStoreManager();
        Object[] objectArray0 = new Object[5];
        JDBCFetchConfigurationImpl jDBCFetchConfigurationImpl0 = new JDBCFetchConfigurationImpl();
        RuntimeExceptionTranslator runtimeExceptionTranslator0 = mock(RuntimeExceptionTranslator.class, new ViolatedAssumptionAnswer());
        DelegatingJDBCFetchConfiguration delegatingJDBCFetchConfiguration0 = new DelegatingJDBCFetchConfiguration(jDBCFetchConfigurationImpl0, runtimeExceptionTranslator0);
        ExpContext expContext0 = new ExpContext(jDBCStoreManager0, objectArray0, delegatingJDBCFetchConfiguration0);
        Class<HandlerRelationMapTableFieldStrategy> class0 = HandlerRelationMapTableFieldStrategy.class;
        Variable variable0 = new Variable((String) null, class0);
        PCPath pCPath0 = new PCPath((ClassMapping) null, variable0);
        All all0 = new All(variable0);
        ExpState expState0 = all0.initialize((Select) null, expContext0, 0);
        // Undeclared exception!
        try {
            pCPath0.select((Select) null, expContext0, expState0, false);
            fail("Expecting exception: NullPointerException");

        } catch(NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("org.apache.openjpa.jdbc.kernel.exps.PCPath", e);
        }
    }

    @Test(timeout = 4000)
    public void test64()  throws Throwable  {
        PCPath pCPath0 = new PCPath((ClassMapping) null);
        pCPath0.setMetaData((ClassMetaData) null);
        assertFalse(pCPath0.isKey());
        assertFalse(pCPath0.isVariablePath());
    }

    @Test(timeout = 4000)
    public void test65()  throws Throwable  {
        PCPath pCPath0 = null;
        try {
            pCPath0 = new PCPath((SubQ) null);
            fail("Expecting exception: NullPointerException");

        } catch(NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("org.apache.openjpa.jdbc.kernel.exps.PCPath", e);
        }
    }

    @Test(timeout = 4000)
    public void test66()  throws Throwable  {
        PCPath pCPath0 = new PCPath((ClassMapping) null);
        int int0 = pCPath0.getId();
        assertFalse(pCPath0.isVariablePath());
        assertFalse(pCPath0.isKey());
        assertEquals(0, int0);
    }

    @Test(timeout = 4000)
    public void test67()  throws Throwable  {
        Class<RelationMapInverseKeyFieldStrategy> class0 = RelationMapInverseKeyFieldStrategy.class;
        Variable variable0 = new Variable("08006", class0);
        PCPath pCPath0 = new PCPath((ClassMapping) null, variable0);
        pCPath0.addVariableAction(variable0);
        assertFalse(pCPath0.isKey());
        assertFalse(pCPath0.isUnaccessedVariable());
        assertTrue(pCPath0.isVariable());
        assertTrue(pCPath0.isVariablePath());
    }
}
