name: Apache OpenJpa CI

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del codice
        uses: actions/checkout@v4

      - name: Setup Java JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build ed Esecuzione esclusiva dei test di progetto
        run: mvn clean test -Dtest="*PCDataImpl*,*PCPath*" -Denforcer.skip=true -Dcheckstyle.skip=true -Drat.skip=true
